---
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=.bandit.yaml
        files: ^package_name/.+\.py$
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        language_version: python3
        files: ^((package_name|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.json"
          - --quiet-level=4
          - -L ba
        exclude_types: [json]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
          - pydocstyle
        files: ^package_name/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - toml
        files: ^(package_name|tests)/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        files: ^package_name/.+\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
        files: ^((package_name|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: shellcheck
        files: ^script/.+
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
