"""Define package constants."""
CONF_CONFIG = "config"
CONF_LIMIT = "limit"
CONF_OFFSET = "offset"
CONF_QUERY = "query"
CONF_TOKEN = "token"
CONF_URL = "url"
CONF_VERBOSE = "verbose"

ENV_CONFIG = "LINKDING_CONFIG"
ENV_TOKEN = "LINKDING_TOKEN"
ENV_URL = "LINKDING_URL"
